server:
  port: ${PORT:8765}
  
logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE

security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
      
zuul:
  routes:  
    aluguel:
      url: http://localhost:8080/aluguel
      serviceId: aluguel
    auth:
      url: http://localhost:8888/auth
      serviceId: auth